name: ui_widget
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  imagebutton: ^1.0.0
  flutter_animated_button: ^2.0.4
  audioplayers: ^6.5.1
  material_segmented_control: ^5.0.1
  lottie: ^3.3.2
  flutter_material_pickers: ^3.7.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  flutter_font_picker: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie/

  fonts:
    - family: PairPlay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
